development:
  adapter: postgresql
  encoding: unicode
  database: forge_dev
  pool: 5
  host: localhost
  port: 5432
  username: <%= ENV.fetch('DB_USER') %>
  password: <%= ENV.fetch('DB_PASSWORD') %>

test:
  adapter: postgresql
  encoding: unicode
  database: forge_test
  pool: 5
  host: localhost
  port: 5432
  username: <%= ENV.fetch('DB_USER') %>
  password: <%= ENV.fetch('DB_PASSWORD') %>

production:
  adapter: postgresql
  encoding: unicode
  database: forge_production
  pool: 5
  password:
