development:
  adapter: postgresql
  encoding: unicode
  database: forge_dev
  pool: 5
  host: localhost
  port: 5432
  username: postgres
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: forge_test
  pool: 5
  host: localhost
  port: 5432
  username: postgres
  password: password

production:
  adapter: postgresql
  encoding: unicode
  database: forge_production
  pool: 5
  password:
